---
# tasks file for ansible-role-epel

- name: "Install epel repo"
  yum:
    name: "{{ epel.repo_http_url }}"
    state: present

- name: "Import epel repo key"
  rpm_key:
    key: "{{ epel.gpg_key_path }}"
    state: present